import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "../../..");
const sketchPath = resolve(repoRoot, "docs/contracts/admin.openapi.yaml");
const generatedDir = resolve(dirname(fileURLToPath(import.meta.url)), "../src/generated");
const typesPath = resolve(generatedDir, "admin-api.d.ts");
const clientPath = resolve(generatedDir, "admin-client.ts");

execFileSync(
  "pnpm",
  [
    "--filter",
    "@webhook-broadcast/contract",
    "exec",
    "openapi-typescript",
    sketchPath,
    "-o",
    typesPath,
  ],
  { cwd: repoRoot, stdio: "inherit" },
);

writeFileSync(
  clientPath,
  `// Generated by packages/contract/scripts/generate-admin-client.ts — do not edit.
import createClient, { type Client } from "openapi-fetch";
import type { paths } from "./admin-api.js";

function adminBaseUrl(): string {
  if (typeof window !== "undefined" && window.location?.origin) {
    return window.location.origin;
  }
  return "http://localhost";
}

let client: Client<paths> | undefined;

/** Test-only: drop cached client so the next call binds the current global fetch. */
export function resetAdminFetchClientForTests(): void {
  client = undefined;
}

/** Typed fetch client for the published admin OpenAPI contract. */
export function getAdminFetchClient(): Client<paths> {
  client ??= createClient<paths>({
    baseUrl: adminBaseUrl(),
    credentials: "include",
    headers: { "content-type": "application/json" },
    fetch: (input: RequestInfo | URL, init?: RequestInit) => globalThis.fetch(input, init),
  });
  return client;
}

export type { paths };
`,
  "utf8",
);

console.log(`Wrote ${typesPath} and ${clientPath}`);
